version: '3.8'
services:
  postgresql14:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: 'informatica'
      POSTGRES_DB: 'postgres'
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432"
  payara5:
    image: tuxtor/payara-demo:1.0-SNAPSHOT
    restart: always
    environment:
      JVM_ARGS: '-Xms1800m -Xmx1800m -XX:+UseG1GC -XX:+UseStringDeduplication'
      PAYARA_URL: 'jdbc:postgresql://postgresql14:5432/postgres'
      PAYARA_DB_PASSWORD: 'informatica'
      PAYARA_SERVER_HOST: 'postgresql14'
    ports:
      - "4848:4848"
      - "8080:8080"
      - "8181:8181"
    depends_on:
      - postgresql14
volumes:
  database-data:
  server-data:
